return {
    -- "jackMort/ChatGPT.nvim",
    -- event = "VeryLazy",
    -- config = function()
    --     require("chatgpt").setup {
    --         model = "gpt-4o-2024-05-13",
    --         openai_params = {
    --
    --             model = "gpt-4o-2024-05-13",
    --             -- model = "gpt-3.5-turbo",
    --             frequency_penalty = 0,
    --             presence_penalty = 0,
    --             max_tokens = 300,
    --             temperature = 0,
    --             top_p = 1,
    --             n = 1,
    --         },
    --         openai_edit_params = {
    --             model = "gpt-4o-2024-05-13",
    --             -- model = "gpt-3.5-turbo",
    --             frequency_penalty = 0,
    --             presence_penalty = 0,
    --             temperature = 0,
    --             top_p = 1,
    --             n = 1,
    --         },
    --     }
    -- end,
    -- dependencies = {
    --     "MunifTanjim/nui.nvim",
    --     "nvim-lua/plenary.nvim",
    --     "folke/trouble.nvim",
    --     "nvim-telescope/telescope.nvim",
    -- },
}

